### ISSUE TITLE
Compatibility with Ubuntu

### ISSUE THREAD

**Issue by Vifespoir** [hamiltron/py-simple-audio#13]
Hi Hamiltron,

First of all, thank you for your great library!

I noticed that while trying to install simple-audio on Ubuntu it failed. It is easily fixed by installing `libasound2-dev` package.

I was thinking that you might want to add a not in the documentation to help people using Ubuntu figure out quickly the solution to this problem.

Thanks again for your great work!

**Comment by hamiltron** [comment]
@Vifespoir, good suggestion... but I actually already have included a note about this (if not very prominently) in the docs [here](http://simpleaudio.readthedocs.io/en/latest/installation.html#linux-dependencies). ;) 

Thanks for using!
