### ISSUE TITLE
Could not create playback thread Code 11

### ISSUE THREAD

**Issue by WIsbrecht** [hamiltron/py-simple-audio#16]
I'm getting sporadic "Could not create playback thread" errors on a raspberry 1.  
It seems that playback_thread() does call pthread_exit() but isn't releasing thread resources.
One might want to call pthread_detach(pthread_self()) inside playback_thread() in order to release all resources at thread termination.

**Comment by hamiltron** [comment]
OK, several months later this is fixed. Big thanks to @WIsbrecht and @jplitza (who made the fix PR). The fix is in [1.0.2](https://pypi.python.org/pypi/simpleaudio/1.0.2)
