### ISSUE TITLE
Allow a program to set the volume and maybe which speaker/channel

### ISSUE THREAD

**Issue by pvcraven** [hamiltron/py-simple-audio#21]
It would be nice if you could set the volume and/or the speaker/balance volume.

**Comment by hamiltron** [comment]
These kinds of controls fall pretty firmly in what I would call the 'mixer' functions of an audio interface. They are obviously very useful, but building a cross-platform API for these functions would likely involve as much work as what has gone into the whole project so far so, for now, it's pretty low on the priority list.

**Comment by hamiltron** [comment]
At this point I have no intention of including mixer controls into the package. If implemented, I would probably make that a completely separate package. The example provided by @hmoravec is a perfect demonstration of adjusting volume using signal processing techniques.
