### ISSUE TITLE
trouble cloning repo with anaconda on windows

### ISSUE THREAD

**Issue by trevoralder** [hamiltron/py-simple-audio#23]
I am using Anaconda3 on windows 10, and when I try
pip install git+https://github.com/hamiltron/py-simple-audio

I get the error
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by FabAlchemy** [comment]
Hi! How did you solve this? Microsoft Visual C++ 14.0 is already installed on my computer but it's still not compiling 😢
