### ISSUE TITLE
play just on left or right channel

### ISSUE THREAD

**Issue by GOBish** [hamiltron/py-simple-audio#25]
In the function checks, playback is separated into left and right channels.

Is there any way to do this for playing a wav?

Is there a way to put this in the play_obj = wave_obj.play() 
as a parameter?

**Comment by hamiltron** [comment]
@GOBish , there are no parameters that let you do this, but it can be fairly easily accomplished by creating an array compatible with 2-channel/stereo audio, and filling one channel with the audio and the other with zeros.
