### ISSUE TITLE
All tests fail with Python 3.7 on Windows 10

### ISSUE THREAD

**Issue by sammosummo** [hamiltron/py-simple-audio#30]
On Windows 10, fully up to date. Installed Python 3.7 via Anaconda, also up to date. `pip install simpleaudio` installs the package fine but all of the tests fail with the message:

```
_simpleaudio.SimpleaudioError: Failed to open audio device. -- CODE: 2 -- MSG: A device ID has been used that is out of range for your system.
```

**Comment by hamiltron** [comment]
Thanks for bringing this to attention. I'll dig into this as soon as I'm able.

**Comment by hamiltron** [comment]
Since updating the builds to include 3.7 and 3.8, I'm not seeing any issues with Windows 10. It's possible this could be an issue with hardware/drivers/etc, so more information would be required here.
