### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by sirin2020** [hamiltron/py-simple-audio#41]
Hello 

I wanted to use simpleaudio in my project and tried to install it using pip" pip3 install simpleaudio", but I get the error bellow : 
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`
python version :  Python 3.6.9
![simpleaudioERROR](https://user-images.githubusercontent.com/65354813/85740386-7ee0e000-b6f9-11ea-9c69-28954eaf2dbe.JPG)

**Comment by bnoland** [comment]
You need the ALSA development files. If you're on Debian or a variant (e.g., Ubuntu), this should work:

`sudo apt-get install libasound2-dev`

(See also: [https://simpleaudio.readthedocs.io/en/latest/installation.html](url)).

If you're on another distribution, take a look around the corresponding package index to find the right package.

Hope this helps.
